### ISSUE TITLE
I've improved the Sentiment-Analyzer project and included it in the awesome-streamlit.org gallery. Hope it's ok?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [patidarparas13/Sentiment-Analyzer-Tool#1]
Hi Patidar

I'm reaching out because I saw your awesome Sentiment-Analyzer-Tool developed in Streamlit. 

I think it's so awesome that I wanted to included it in the [awesome-streamlit.org](https://awesome-streamlit.org/) Gallery. I hope that is OK?

In order to include it I had to refactor it so that the files are not loaded from the file folder. 

And then I took a look and did a larger refactoring of the layout and flow. After that I thought that I had done so many things that it was ok to credit the two of us in the way shown below. I hope it is Ok?

![image](https://user-images.githubusercontent.com/42288570/66714425-0b8b7e00-edb7-11e9-98fe-b8cfad50f73d.png)

You're welcome to publish your awesome streamlit examples with you as Author at https://github.com/marcskovmadsen/awesome-streamlit. It's only a pull request away :-)

Please note I have yet to solve some performance issues on Azure where it's deployed. The awesome-streamlit app is really fast locally :-)

Thanks.

Marc

**Comment by patidarparas13** [comment]
Thanks, @MarcSkovMadsen for including my project and I am good with the improvements you have done.
